# lightning.pytorch==2.1.2
seed_everything: 42
data:
  train_chip_dir: data/processed/chips/npy/512/train/chips/
  train_label_dir: data/processed/chips/npy/512/train/labels/
  val_chip_dir: data/processed/chips/npy/512/val/chips/
  val_label_dir: data/processed/chips/npy/512/val/labels/
  metadata_path: configs/cnn/cnn_segment_metadata.yaml
  batch_size: 16
  num_workers: 16 # Set to number of CPU cores
  platform: sentinel-2-l2a
  data_augmentation: True
model:
  arch: unet
  encoder_name: resnet34
  encoder_weights: imagenet
  in_channels: 3
  num_classes: 1
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  log_every_n_steps: 2
  max_epochs: 18
  accumulate_grad_batches: 1
  default_root_dir: src/models/cnn
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: s-jasansky-Maastricht University
        project: mine-segmentation-cnn
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: models/cnn
        auto_insert_metric_name: False
        filename: mineseg-cnn_epoch-{epoch:02d}_val-iou-{val/iou:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 1
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO