name: cloudspace
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - rioxarray
  - stackstac
  - geopandas
  - shapely
  - leafmap
  - ipykernel
  - jupyter-server-proxy
  - localtileserver
  - numpy
  - requests
  - pandas
  - matplotlib
  - Pillow
  - scikit-image
  - seaborn
  - streamlit
  - flask 
  - flask-restx
  - pip
  - pip:
    - pystac_client
    - planetary_computer