channels:
  - conda-forge
  - defaults
dependencies:
  # base
  - rasterio
  - rioxarray
  - stackstac
  - geopandas
  - shapely
  - leafmap
  - ipykernel
  - jupyter-server-proxy
  - localtileserver
  - numpy
  - requests
  - pandas
  - matplotlib
  - Pillow
  - scikit-image
  - seaborn
  - streamlit
  - flask
  - flask-restx
  - pip
  # clay
  - pytorch
  - lightning
  - transformers
  - torchvision
  - vit-pytorch
  - einops
  - python-box
  - pip:
    # base
    - pystac_client
    - planetary_computer
    # clay
    - timm