# lightning.pytorch==2.1.2
seed_everything: 42
data:
  train_chip_dir: data/processed/chips/train/chips/
  train_label_dir: data/processed/chips/train/labels/
  val_chip_dir: data/processed/chips/val/chips/
  val_label_dir: data/processed/chips/val/labels/
  metadata_path: configs/clay_segment_metadata.yaml
  batch_size: 6
  num_workers: 16 # Set to number of CPU cores
  platform: sentinel-2-l2a
model:
  num_classes: 1
  feature_maps:
    - 3
    - 5
    - 7
    - 11
  ckpt_path: models/clay-v1-base.ckpt
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  log_every_n_steps: 2
  max_epochs: 10
  accumulate_grad_batches: 1
  default_root_dir: src/models/clay
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: s-jasansky-Maastricht University
        project: mine-segmentation
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: models
        auto_insert_metric_name: False
        filename: mineseg-2class-segment_epoch-{epoch:02d}_val-iou-{val/iou:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO