sentinel-2-l2a:
  band_order:
    - B02
    - B03
    - B04
#    - B08
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 10
  bands:
    mean:
      B02: 1105.
      B03: 1355.
      B04: 1552.
#      B08: 2743.
    std:
      B02: 1809.
      B03: 1757.
      B04: 1888.
#      B08: 1742.
    wavelength:
      B02: 0.493
      B03: 0.56
      B04: 0.665
#      B08: 0.842

